version: "3.8"
services:
  sslproxy:
    build:
      context: ./nginx/
    ports:
      - 3001:443
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend/
    volumes:
      - ./.env:/app/.env:ro
    restart: unless-stopped

  backend:
    build:
      context: ./backend/
    environment:
      NODE_ENV: production
      DB_HOST: ${DB_HOST}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./.env:/app/.env:ro
    restart: unless-stopped
    depends_on:
      - db

  db:
    image: postgres:16
    volumes:
      - ./postgres:/var/lib/postgresql/data
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  # adminer:
  #   image: adminer
  #   restart: unless-stopped
  #   environment:
  #     - ADMINER_DEFAULT_SERVER=pgsql
  #   ports:
  #     - 8080:8080
  #   depends_on:
  #     - db
